Check if tests passed

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -45,3 +45,11 @@ runs:
         TESTS_DIRECTORY: ${{ inputs.testsDirectory }}
         QUIT_MUDLET_AFTER_TESTS: 'true'
         PRETEST_PACKAGE: ${{ inputs.preTestPackage }}
+      
+    - name: Passed Lua tests
+      run: |
+        if [ -e /tmp/busted-tests-failed ]
+        then
+          echo "Lua tests failed - see the action above for detailed output."
+          exit 1
+        fi
